const fs = require('fs');

const enPath = 'frontend/src/locales/en.json';
const hiPath = 'frontend/src/locales/hi.json';
const tePath = 'frontend/src/locales/te.json';

const en = JSON.parse(fs.readFileSync(enPath, 'utf8'));
const hi = JSON.parse(fs.readFileSync(hiPath, 'utf8'));
const te = JSON.parse(fs.readFileSync(tePath, 'utf8'));

// Profile
en.settings.profile_info = {
  title: "Profile Information",
  full_name: "Full Name",
  email: "Email Address",
  phone: "Phone Number",
  language: "Language",
  save: "Save Changes",
  saving: "Saving...",
  danger_zone: "Danger Zone",
  danger_desc: "Disconnect from your session or permanently delete your account.",
  sign_out: "Sign Out"
};

te.settings.profile_info = {
  title: "ప్రొఫైల్ సమాచారం",
  full_name: "పూర్తి పేరు",
  email: "ఇమెయిల్ చిరునామా",
  phone: "ఫోన్ నంబర్",
  language: "భాష",
  save: "మార్పులను సేవ్ చేయండి",
  saving: "సేవ్ అవుతోంది...",
  danger_zone: "డేంజర్ జోన్",
  danger_desc: "మీ సెషన్ నుండి డిస్‌కనెక్ట్ చేయండి లేదా మీ ఖాతాను శాశ్వతంగా తొలగించండి.",
  sign_out: "సైన్ అవుట్"
};

hi.settings.profile_info = {
  title: "प्रोफ़ाइल जानकारी",
  full_name: "पूरा नाम",
  email: "ईमेल पता",
  phone: "फ़ोन नंबर",
  language: "भाषा",
  save: "परिवर्तन सहेजें",
  saving: "सहेजा जा रहा है...",
  danger_zone: "खतरे का क्षेत्र",
  danger_desc: "अपने सत्र से डिस्कनेक्ट करें या अपना खाता स्थायी रूप से हटाएं।",
  sign_out: "साइन आउट"
};

// Accounts
en.settings.accounts = {
  title: "Linked Accounts & Data Sources",
  desc: "FinSaathi uses manual statement uploads to ground AI insights. Your connected data sources are listed below.",
  no_accounts: "No financial accounts connected yet.",
  upload: "Upload Statement",
  statement_based: "Statement-based account",
  last_updated: "Last updated:",
  active: "Active",
  processing: "Processing",
  view_transactions: "View Transactions"
};

te.settings.accounts = {
  title: "లింక్ చేయబడిన ఖాతాలు & డేటా మూలాలు",
  desc: "AI అంతర్దృష్టులను అందించడానికి FinSaathi మాన్యువల్ స్టేట్‌మెంట్ అప్‌లోడ్‌లను ఉపయోగిస్తుంది. మీ కనెక్ట్ చేయబడిన డేటా మూలాలు క్రింద జాబితా చేయబడ్డాయి.",
  no_accounts: "ఇంకా ఎలాంటి ఆర్థిక ఖాతాలు కనెక్ట్ కాలేదు.",
  upload: "స్టేట్‌మెంట్‌ను అప్‌లోడ్ చేయండి",
  statement_based: "స్టేట్‌మెంట్-ఆధారిత ఖాతా",
  last_updated: "చివరిగా అప్‌డేట్ చేయబడినది:",
  active: "క్రియాశీలం",
  processing: "ప్రాసెస్ అవుతోంది",
  view_transactions: "లావాదేవీలను చూడండి"
};

hi.settings.accounts = {
  title: "लिंक किए गए खाते और डेटा स्रोत",
  desc: "AI अंतर्दृष्टि प्रदान करने के लिए FinSaathi मैन्युअल स्टेटमेंट अपलोड का उपयोग करता है। आपके कनेक्टेड डेटा स्रोत नीचे सूचीबद्ध हैं।",
  no_accounts: "अभी तक कोई वित्तीय खाता नहीं जुड़ा है।",
  upload: "स्टेटमेंट अपलोड करें",
  statement_based: "स्टेटमेंट-आधारित खाता",
  last_updated: "अंतिम अपडेट:",
  active: "सक्रिय",
  processing: "प्रसंस्करण",
  view_transactions: "लेनदेन देखें"
};

// Notifications
en.settings.notifications = {
  title: "Notification Preferences",
  transaction_alerts: "Transaction Alerts",
  transaction_alerts_desc: "Get notified about unusual transactions or large expenses.",
  budget_alerts: "Budget Alerts",
  budget_alerts_desc: "Receive warnings when you are approaching your budget limits.",
  goal_reminders: "Goal Reminders",
  goal_reminders_desc: "Get reminders and updates on your savings goals progress.",
  subscription_reminders: "Subscription Reminders",
  subscription_reminders_desc: "Get alerted before upcoming subscription renewals.",
  ai_insights: "AI Insights",
  ai_insights_desc: "Receive personalized financial insights generated by FinSaathi AI.",
  security_alerts: "Security Alerts",
  security_alerts_desc: "Important notifications about your account security.",
  save: "Save Preferences",
  saving: "Saving..."
};

te.settings.notifications = {
  title: "నోటిఫికేషన్ ప్రాధాన్యతలు",
  transaction_alerts: "లావాదేవీ హెచ్చరికలు",
  transaction_alerts_desc: "అసాధారణ లావాదేవీలు లేదా పెద్ద ఖర్చుల గురించి నోటిఫికేషన్ పొందండి.",
  budget_alerts: "బడ్జెట్ హెచ్చరికలు",
  budget_alerts_desc: "మీరు మీ బడ్జెట్ పరిమితులను సమీపిస్తున్నప్పుడు హెచ్చరికలను స్వీకరించండి.",
  goal_reminders: "లక్ష్య రిమైండర్‌లు",
  goal_reminders_desc: "మీ పొదుపు లక్ష్యాల పురోగతిపై రిమైండర్‌లు మరియు నవీకరణలను పొందండి.",
  subscription_reminders: "సబ్‌స్క్రిప్షన్ రిమైండర్‌లు",
  subscription_reminders_desc: "రాబోయే సబ్‌స్క్రిప్షన్ పునరుద్ధరణలకు ముందు అప్రమత్తం అవ్వండి.",
  ai_insights: "AI విశ్లేషణలు",
  ai_insights_desc: "FinSaathi AI రూపొందించిన వ్యక్తిగతీకరించిన ఆర్థిక విశ్లేషణలను పొందండి.",
  security_alerts: "భద్రతా హెచ్చరికలు",
  security_alerts_desc: "మీ ఖాతా భద్రత గురించి ముఖ్యమైన నోటిఫికేషన్‌లు.",
  save: "ప్రాధాన్యతలను సేవ్ చేయండి",
  saving: "సేవ్ అవుతోంది..."
};

hi.settings.notifications = {
  title: "अधिसूचना प्राथमिकताएं",
  transaction_alerts: "लेनदेन अलर्ट",
  transaction_alerts_desc: "असामान्य लेनदेन या बड़े खर्चों के बारे में सूचना प्राप्त करें।",
  budget_alerts: "बजट अलर्ट",
  budget_alerts_desc: "जब आप अपनी बजट सीमा के करीब पहुंच रहे हों तो चेतावनी प्राप्त करें।",
  goal_reminders: "लक्ष्य अनुस्मारक",
  goal_reminders_desc: "अपने बचत लक्ष्यों की प्रगति पर अनुस्मारक और अपडेट प्राप्त करें।",
  subscription_reminders: "सदस्यता अनुस्मारक",
  subscription_reminders_desc: "आगामी सदस्यता नवीनीकरण से पहले सतर्क हो जाएं।",
  ai_insights: "AI अंतर्दृष्टि",
  ai_insights_desc: "FinSaathi AI द्वारा उत्पन्न व्यक्तिगत वित्तीय अंतर्दृष्टि प्राप्त करें।",
  security_alerts: "सुरक्षा अलर्ट",
  security_alerts_desc: "आपके खाते की सुरक्षा के बारे में महत्वपूर्ण सूचनाएं।",
  save: "प्राथमिकताएं सहेजें",
  saving: "सहेजा जा रहा है..."
};

// Security
en.settings.security = {
  title: "Security Settings",
  change_password: "Change Password",
  current_password: "Current Password",
  new_password: "New Password",
  confirm_password: "Confirm New Password",
  update_password: "Update Password",
  updating: "Updating...",
  active_sessions: "Active Sessions",
  current_device: "Current Device",
  current_device_desc: "You are currently signed in on this device.",
  sign_out_device: "Sign out of this device",
  security_status: "Security Status",
  password_last_changed: "Password last changed",
  account_created: "Account created"
};

te.settings.security = {
  title: "భద్రతా సెట్టింగ్‌లు",
  change_password: "పాస్‌వర్డ్ మార్చండి",
  current_password: "ప్రస్తుత పాస్‌వర్డ్",
  new_password: "కొత్త పాస్‌వర్డ్",
  confirm_password: "కొత్త పాస్‌వర్డ్ నిర్ధారించండి",
  update_password: "పాస్‌వర్డ్‌ను అప్‌డేట్ చేయండి",
  updating: "అప్‌డేట్ అవుతోంది...",
  active_sessions: "సక్రియ సెషన్‌లు",
  current_device: "ప్రస్తుత పరికరం",
  current_device_desc: "మీరు ప్రస్తుతం ఈ పరికరంలో సైన్ ఇన్ చేసి ఉన్నారు.",
  sign_out_device: "ఈ పరికరం నుండి సైన్ అవుట్ చేయండి",
  security_status: "భద్రతా స్థితి",
  password_last_changed: "పాస్‌వర్డ్ చివరిగా మార్చబడినది",
  account_created: "ఖాతా సృష్టించబడినది"
};

hi.settings.security = {
  title: "सुरक्षा सेटिंग्स",
  change_password: "पासवर्ड बदलें",
  current_password: "वर्तमान पासवर्ड",
  new_password: "नया पासवर्ड",
  confirm_password: "नए पासवर्ड की पुष्टि करें",
  update_password: "पासवर्ड अपडेट करें",
  updating: "अपडेट हो रहा है...",
  active_sessions: "सक्रिय सत्र",
  current_device: "वर्तमान उपकरण",
  current_device_desc: "आप वर्तमान में इस उपकरण पर साइन इन हैं।",
  sign_out_device: "इस उपकरण से साइन आउट करें",
  security_status: "सुरक्षा स्थिति",
  password_last_changed: "पासवर्ड अंतिम बार बदला गया",
  account_created: "खाता बनाया गया"
};

// Support
en.settings.support = {
  title: "Help & Support",
  desc: "Find answers to common questions or reach out to our team.",
  faq_title: "Frequently Asked Questions",
  contact_title: "Contact Support",
  how_can_we_help: "How can we help?",
  placeholder: "Describe your issue or question...",
  send: "Send Request",
  privacy_title: "Privacy & Data",
  privacy_1: "Financial data belongs solely to you.",
  privacy_2: "Users cannot access another user's transactions or documents.",
  privacy_3: "AI responses are grounded exclusively in your own uploaded financial data.",
  faqs: [
    {
      q: "How do I upload a bank statement?",
      a: "Go to the Transactions page and click the 'Upload Statement' button. You can upload PDF bank statements or Excel exports. Our AI will automatically extract and categorize the transactions."
    },
    {
      q: "How does FinSaathi calculate spending?",
      a: "FinSaathi aggregates all debit transactions from your uploaded statements and categorizes them using AI. It excludes internal transfers and focuses only on actual expenses."
    },
    {
      q: "How does AI use my financial data?",
      a: "The AI only accesses the transaction and document data you have explicitly uploaded. It uses this data locally in an isolated session to answer your specific questions in the Chat interface."
    },
    {
      q: "How can I delete my financial data?",
      a: "You can delete your entire account and all associated data from the Profile Settings page. You can also delete individual documents from the Transactions page."
    },
    {
      q: "Are my API credentials protected?",
      a: "Yes, API keys like Groq are stored securely on the backend server environment variables. They are never exposed to the frontend browser."
    }
  ]
};

te.settings.support = {
  title: "సహాయం & మద్దతు",
  desc: "సాధారణ ప్రశ్నలకు సమాధానాలు కనుగొనండి లేదా మా బృందాన్ని సంప్రదించండి.",
  faq_title: "తరచుగా అడిగే ప్రశ్నలు",
  contact_title: "మద్దతు బృందాన్ని సంప్రదించండి",
  how_can_we_help: "మేము ఎలా సహాయపడగలం?",
  placeholder: "మీ సమస్య లేదా ప్రశ్నను వివరించండి...",
  send: "అభ్యర్థనను పంపండి",
  privacy_title: "గోప్యత & డేటా",
  privacy_1: "ఆర్థిక డేటా పూర్తిగా మీకే చెందినది.",
  privacy_2: "వినియోగదారులు మరొకరి లావాదేవీలు లేదా పత్రాలను యాక్సెస్ చేయలేరు.",
  privacy_3: "AI ప్రతిస్పందనలు మీరు అప్‌లోడ్ చేసిన మీ స్వంత ఆర్థిక డేటాపై మాత్రమే ఆధారపడి ఉంటాయి.",
  faqs: [
    {
      q: "నేను బ్యాంక్ స్టేట్‌మెంట్‌ను ఎలా అప్‌లోడ్ చేయాలి?",
      a: "లావాదేవీల పేజీకి వెళ్లి 'స్టేట్‌మెంట్‌ను అప్‌లోడ్ చేయండి' బటన్‌ను క్లిక్ చేయండి. మీరు PDF బ్యాంక్ స్టేట్‌మెంట్‌లు లేదా ఎక్సెల్ ఎగుమతులను అప్‌లోడ్ చేయవచ్చు. మా AI లావాదేవీలను స్వయంచాలకంగా సంగ్రహిస్తుంది మరియు వర్గీకరిస్తుంది."
    },
    {
      q: "FinSaathi ఖర్చులను ఎలా లెక్కిస్తుంది?",
      a: "FinSaathi మీరు అప్‌లోడ్ చేసిన స్టేట్‌మెంట్‌ల నుండి అన్ని డెబిట్ లావాదేవీలను సమగ్రపరుస్తుంది మరియు AI ని ఉపయోగించి వాటిని వర్గీకరిస్తుంది. ఇది అంతర్గత బదిలీలను మినహాయిస్తుంది మరియు వాస్తవ ఖర్చులపై మాత్రమే దృష్టి పెడుతుంది."
    },
    {
      q: "AI నా ఆర్థిక డేటాను ఎలా ఉపయోగిస్తుంది?",
      a: "AI మీరు స్పష్టంగా అప్‌లోడ్ చేసిన లావాదేవీ మరియు పత్ర డేటాను మాత్రమే యాక్సెస్ చేస్తుంది. చాట్ ఇంటర్‌ఫేస్‌లో మీ నిర్దిష్ట ప్రశ్నలకు సమాధానం ఇవ్వడానికి ఇది ఈ డేటాను స్థానికంగా ఐసోలేటెడ్ సెషన్‌లో ఉపయోగిస్తుంది."
    },
    {
      q: "నా ఆర్థిక డేటాను నేను ఎలా తొలగించగలను?",
      a: "మీరు ప్రొఫైల్ సెట్టింగ్‌ల పేజీ నుండి మీ మొత్తం ఖాతాను మరియు అనుబంధిత డేటా మొత్తాన్ని తొలగించవచ్చు. మీరు లావాదేవీల పేజీ నుండి వ్యక్తిగత పత్రాలను కూడా తొలగించవచ్చు."
    },
    {
      q: "నా API ఆధారాలు రక్షించబడ్డాయా?",
      a: "అవును, Groq వంటి API కీలు బ్యాకెండ్ సర్వర్ ఎన్విరాన్‌మెంట్ వేరియబుల్స్‌లో సురక్షితంగా నిల్వ చేయబడతాయి. అవి ఎప్పుడూ ఫ్రంటెండ్ బ్రౌజర్‌కు బహిర్గతం కావు."
    }
  ]
};

hi.settings.support = {
  title: "सहायता और समर्थन",
  desc: "सामान्य प्रश्नों के उत्तर खोजें या हमारी टीम से संपर्क करें।",
  faq_title: "अक्सर पूछे जाने वाले प्रश्न",
  contact_title: "समर्थन से संपर्क करें",
  how_can_we_help: "हम कैसे मदद कर सकते हैं?",
  placeholder: "अपनी समस्या या प्रश्न का वर्णन करें...",
  send: "अनुरोध भेजें",
  privacy_title: "गोपनीयता और डेटा",
  privacy_1: "वित्तीय डेटा पूरी तरह से आपका है।",
  privacy_2: "उपयोगकर्ता किसी अन्य उपयोगकर्ता के लेनदेन या दस्तावेजों तक नहीं पहुंच सकते हैं।",
  privacy_3: "AI प्रतिक्रियाएं विशेष रूप से आपके अपने अपलोड किए गए वित्तीय डेटा पर आधारित होती हैं।",
  faqs: [
    {
      q: "मैं बैंक स्टेटमेंट कैसे अपलोड करूं?",
      a: "लेनदेन पृष्ठ पर जाएं और 'स्टेटमेंट अपलोड करें' बटन पर क्लिक करें। आप पीडीएफ बैंक स्टेटमेंट या एक्सेल निर्यात अपलोड कर सकते हैं। हमारा AI स्वचालित रूप से लेनदेन को निकालता है और वर्गीकृत करता है।"
    },
    {
      q: "FinSaathi खर्च की गणना कैसे करता है?",
      a: "FinSaathi आपके अपलोड किए गए स्टेटमेंट से सभी डेबिट लेनदेन को एकत्रित करता है और AI का उपयोग करके उन्हें वर्गीकृत करता है। यह आंतरिक हस्तांतरण को छोड़कर केवल वास्तविक खर्चों पर ध्यान केंद्रित करता है।"
    },
    {
      q: "AI मेरे वित्तीय डेटा का उपयोग कैसे करता है?",
      a: "AI केवल उसी लेनदेन और दस्तावेज़ डेटा तक पहुँचता है जिसे आपने स्पष्ट रूप से अपलोड किया है। यह चैट इंटरफ़ेस में आपके विशिष्ट प्रश्नों का उत्तर देने के लिए एक अलग सत्र में स्थानीय रूप से इस डेटा का उपयोग करता है।"
    },
    {
      q: "मैं अपना वित्तीय डेटा कैसे हटा सकता हूं?",
      a: "आप प्रोफ़ाइल सेटिंग्स पृष्ठ से अपने संपूर्ण खाते और सभी संबद्ध डेटा को हटा सकते हैं। आप लेनदेन पृष्ठ से व्यक्तिगत दस्तावेजों को भी हटा सकते हैं।"
    },
    {
      q: "क्या मेरे API क्रेडेंशियल सुरक्षित हैं?",
      a: "हाँ, Groq जैसी API कुंजियाँ बैकएंड सर्वर पर्यावरण चर पर सुरक्षित रूप से संग्रहीत हैं। वे कभी भी फ्रंटएंड ब्राउज़र के संपर्क में नहीं आते हैं।"
    }
  ]
};

fs.writeFileSync(enPath, JSON.stringify(en, null, 2));
fs.writeFileSync(tePath, JSON.stringify(te, null, 2));
fs.writeFileSync(hiPath, JSON.stringify(hi, null, 2));
